version: '3.8'

services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
    working_dir: /var/www
    networks:
      - app_network
      
  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: unless-stopped
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - app_network

  # MySQL Service
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app_network

  # Node.js Service
  node:
    image: node:latest
    container_name: laravel_node
    volumes:
      - ./:/var/www
    working_dir: /var/www
    command: npm install
    networks:
      - app_network

# Networks
networks:
  app_network:
    driver: bridge
    
# Volumes
volumes:
  dbdata: